# Generated by Django 3.0.5 on 2020-05-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200502_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('REC', 'Recruiting Agency'), ('EMP', 'Potential Employer')], default='EMP', max_length=3),
        ),
    ]
