# Generated by Django 3.0.5 on 2020-05-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New Opportunity'), ('APP', 'Application Submitted'), ('INT', 'Interviewing'), ('AWD', 'Awaiting Decision')], default='NEW', max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Company')),
            ],
        ),
    ]
