# Generated by Django 3.0.5 on 2020-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Sample Job Title', max_length=255),
            preserve_default=False,
        ),
    ]
