# Generated by Django 3.0.5 on 2020-05-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Opportunity'), ('APP', 'Application Submitted'), ('INT', 'Interviewing'), ('AWD', 'Awaiting Decision'), ('NGO', 'Negotiating Offer'), ('ACP', 'Accepted Offer'), ('DCL', 'Declined Offer'), ('STP', 'Stopped Pursuing'), ('REJ', 'Rejected')], default='NEW', max_length=3),
        ),
    ]
